{
 "title": "Analytical dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Monthly co2 delta",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  bucket AS \"time\",\n  avg_delta AS \"Delta CO2\"\nFROM statistics_monthly_co2\nWHERE $__timeFilter(bucket)\nORDER BY bucket ASC;\n"
    }
   ]
  },
  {
   "title": "Co2 delta difference",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  AVG(avg_pressure_delta) AS \"Delta\"\nFROM statistics_hourly_co2\nWHERE $__timeFilter(bucket);\n"
    }
   ]
  },
  {
   "title": "Machine status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT machine_status FROM statistics\nORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Total cycles",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  bucket AS \"time\",\n  total_cycles\nFROM statistics_hourly_throughput\nWHERE $__timeFilter(bucket)\nORDER BY bucket ASC;\n"
    }
   ]
  },
  {
   "title": "Hourly average cycle time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Cycle time" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  bucket AS \"time\",\n  article,\n  avg_actual_cycle_time AS \"Actual Cycle Time\"\nFROM statistics_hourly_kpis\nWHERE bucket >= now() - interval '24 hours'\nORDER BY bucket ASC;\n"
    }
   ]
  },
  {
   "title": "Cycle time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  time AS \"time\",\n  article,\n  production_order,\n  actual_cycle_time\nFROM statistics\nWHERE $__timeFilter(time)\nORDER BY time ASC;\n"
    }
   ]
  },
  {
   "title": "Cycle time variance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  bucket AS \"time\",\n  stddev_actual_cycle_time AS \"Std Dev Cycle Time\",\n  var_actual_cycle_time AS \"Variance Cycle Time\"\nFROM statistics_hourly_variance\nWHERE $__timeFilter(bucket)\nORDER BY bucket ASC;\n"
    }
   ]
  },
  {
   "title": "CO2 pressure live",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  time AS \"time\",\n  actual_co2_pressure\n  \nFROM statistics\nWHERE $__timeFilter(time)\nORDER BY time ASC;\n"
    }
   ]
  },
  {
   "title": "Weekly average cycle time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  bucket AS \"time\",\n  article,\n  avg_actual_cycle_time AS \"Actual Cycle Time\",\n  avg_target_cycle_time AS \"Target Cycle Time\"\nFROM statistics_weekly_kpis\nWHERE $__timeFilter(bucket)\nORDER BY bucket ASC;"
    }
   ]
  },
  {
   "title": "Machine status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  time AS \"time\",\n  machine_status AS \"status\"\nFROM statistics\nWHERE $__timeFilter(time)\nORDER BY time;\n"
    }
   ]
  }
 ]
}