input:
  kafka:
    addresses:
      - redpanda:9092
    topics:
      - "mqtt_events"
    consumer_group: mqtt_to_timescale
    start_from_oldest: false

pipeline:
  processors:
    - mapping: |
        root.timestamp = this.timestamp
        root.article = this.article
        root.actual_cycle_time = this.actual_cycle_time
        root.order = this.order
        root.target_cycle_time = this.target_cycle_time
        root.actual_co2_pressure = this.co2_pressure
        root.target_co2_pressure = this.target_co2_pressure
        root.machine_status = this.machine_status
    - sql_insert:
        driver: postgres
        dsn: "postgres://postgres:password@timescaledb:5432/postgres?sslmode=disable"
        table: statistics
        columns:
          - time
          - article
          - production_order
          - target_cycle_time
          - actual_cycle_time
          - target_co2_pressure
          - actual_co2_pressure
          - machine_status
        args_mapping: |
          root = [
            this.timestamp,
            this.article,
            this.order,
            this.target_cycle_time,
            this.actual_cycle_time,
            this.target_co2_pressure,
            this.actual_co2_pressure,
            this.machine_status
          ]